# using 30-Days-Of-Python git repository

# Introduction
# Day 1 - 30DaysOfPython Challenge

print(3 + 2)   # addition(+) = 5
print(3 - 2)   # subtraction(-) = 1
print(3 * 2)   # multiplication(*) = 6
print(3 / 2)   # division(/) = 1.5
print(3 ** 2)  # exponential(**) = 9
print(3 % 2)   # modulus(%) remainder = 1
print(3 // 2)  # Floor division operator(//) divides then rounds down = 1

# Checking data types

print(type(10))                  # Int = <class 'int'>
print(type(3.14))                # Float = <class 'float'>
print(type(1 + 3j))              # Complex = <class 'complex'>
print(type('Zack'))          # String = <class 'str'>
print(type([1, 2, 3]))           # List = <class 'list'>
print(type({'name':'Zack'})) # Dictionary = <class 'dict'>
print(type({9.8, 3.14, 2.7}))    # Set = <class 'set'>
print(type((9.8, 3.14, 2.7)))    # Tuple = <class 'tuple'>
print(type(3 == 3))              # Bool = <class 'bool'>
print(type(3 >= 3))              # Bool = <class 'bool'>